### ISSUE TITLE
Home page view - Remove header from description under feature images

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Student-Profiles#4]
Marilynn just brought this up to me. When she is adding a new alumni/student profile, she puts the name of the student in the title bar, and then in the main content creates the copy (header and paragraph). However the blurb of text that shows up on the home page under the spotlight image runs that header right into the body copy. Is there a way to bypass and not include that header on the home page text under the spotlight image? We tried just eliminating the header altogether on the spotlight page but we think it looks a little odd without it.

Thanks!

**Comment by joelworsham** [comment]
Will that header, "Jackson College, shaping people’s lives" **always** be the same text? Or will it change?

If it will not change, I'll hard-code it into the template.

If it *will* change, I'll provide an extra text field for you to enter it, so that it is separated from the content.

**Comment by banksashleym** [comment]
The title will be specific to each alumni/student profile - if you could provide an extra field for the header that would be wonderful.

Thanks!

**Comment by joelworsham** [comment]
Oh also, before Marilynn gets much farther, let's not have you guys manually place the picture of them in the content. I can have the featured image brought in and placed in a column to the right.
