### ISSUE TITLE
Ability to add more profiles

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Student-Profiles#6]
Sorry, just had a staff meeting to discuss these profiles. Dotty brought up the fact that sometimes we might need to feature a "community profile" or "staff profile" or "faculty profile" and not just alumni/student...instead of creating a list of set types (since she mentioned in the future we might not know what types of profiles we need) would it be possible to just do a general profile, and then categorize them by type (with the ability to add more types in the future if need be?)

**Comment by joelworsham** [comment]
Yes we can do that

**Comment by joelworsham** [comment]
All set. You will need to add the banner image again under Profiles -> Settings in the admin screen. (make sure you find the image in the media library, rather than uploading it again)
